### ISSUE TITLE
Linux-64x builds missing from V8 canary on 7/10/19

### ISSUE THREAD

**Issue by nolanmar511** [nodejs/node-v8#112]
* **Version**: V8 canary from 7/10/19
* **Platform**: Linux x64

I tried to download the latest version of the V8 canary build using nvm and got a 404 error:
```
$NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary nvm install node
Downloading and installing node v13.0.0-v8-canary2019071073fa564988...
Downloading https://nodejs.org/download/v8-canary/v13.0.0-v8-canary2019071073fa564988/node-v13.0.0-v8-canary2019071073fa564988-linux-x64.tar.xz...
#=#=#                                                                          
curl: (22) The requested URL returned error: 404 
Binary download from https://nodejs.org/download/v8-canary/v13.0.0-v8-canary2019071073fa564988/node-v13.0.0-v8-canary2019071073fa564988-linux-x64.tar.xz failed, trying source.
...
```

Looking at https://nodejs.org/download/v8-canary/v13.0.0-v8-canary2019071073fa564988/, I see that the files ending with "-linux-x64.tar.xz" and "-linux-x64.tar.gz" are not available for the latest v8 canary build, but were available for the [previous build](https://nodejs.org/download/v8-canary/v13.0.0-v8-canary20190709ae2ab07a38/).

Is this expected?

**Comment by ryzokuken** [comment]
@nolanmar511 this might be because of build failures. @targos any idea what exactly happened?

**Comment by targos** [comment]
The error on Jenkins is:

```
12:00:37  > git fetch --tags --progress https://github.com/nodejs/node-v8.git +refs/heads/*:refs/remotes/origin/* # timeout=30
12:00:37 ERROR: Error fetching remote repo 'origin'
12:00:37 hudson.plugins.git.GitException: Failed to fetch from https://github.com/nodejs/node-v8.git
12:00:37 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
12:00:37 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
12:00:37 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
12:00:37 	at hudson.scm.SCM.checkout(SCM.java:504)
12:00:37 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
12:00:37 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
12:00:37 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:00:37 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
12:00:37 	at hudson.model.Run.execute(Run.java:1816)
12:00:37 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
12:00:37 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:00:37 	at hudson.model.Executor.run(Executor.java:429)
12:00:37 Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/nodejs/node-v8.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
12:00:37 stdout: 
12:00:37 stderr: fatal: unable to access 'https://github.com/nodejs/node-v8.git/': Could not resolve host: github.com; Unknown error
```

Probably a random connection failure. Let's see if it works today (the build will start in ~4 hours from now).

**Comment by ryzokuken** [comment]
Closing this since there’s nothing more to be done. @nolanmar511 I am sorry if this caused any inconvenience, hopefully we will have the Linux builds up today.

@refack could we look into this infra fail and somehow make sure it doesn’t happen again (or maybe make automated retries if it does?)

**Comment by nolanmar511** [comment]
Thanks so much!
I can install the latest release -- glad to see it's not on-going!
