### ISSUE TITLE
Failing test with V8 7.8

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#114]
```
$ out/Release/node /home/mzasso/git/nodejs/canary/test/parallel/test-assert.js
NOTE: The test started as a child_process using these flags: [ '--expose-internals' ] Use NODE_SKIP_FLAG_CHECK to run the test with the original flags.
/home/mzasso/git/nodejs/canary/test/common/index.js:617
        throw new assert.AssertionError({
        ^

AssertionError [ERR_ASSERTION]: Expected "actual" to be reference-equal to "expected":
+ actual - expected

  Comparison {
    code: 'ERR_ASSERTION',
+   message: 'false == true',
-   message: 'The expression evaluated to a falsy value:\n\n  assert(1 === 2)\n',
    type: [Function: AssertionError]
  }
    at new AssertionError (internal/assert/assertion_error.js:418:11)
    at Object.innerFn (/home/mzasso/git/nodejs/canary/test/common/index.js:617:15)
    at expectedException (assert.js:626:24)
    at expectsError (assert.js:728:3)
    at Function.throws (assert.js:777:3)
    at Object.expectsError (/home/mzasso/git/nodejs/canary/test/common/index.js:629:12)
    at Object.<anonymous> (/home/mzasso/git/nodejs/canary/test/parallel/test-assert.js:902:8)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:789:32) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: [AssertionError],
  expected: [Object],
  operator: 'common.expectsError'
}
```

It seems to be a bug in V8. I opened https://bugs.chromium.org/p/v8/issues/detail?id=9634 upstream

**Comment by targos** [comment]
This is a won't fix per https://bugs.chromium.org/p/v8/issues/detail?id=9620

/cc @BridgeAR Do you have an idea on how to fix this?

The issue if that with V8 canary, the following script prints 1 instead of 3:

```
Error.prepareStackTrace = (_, stack) => stack;
--
var fn = new Function('throw new Error("test")');
var err;
try { fn(); } catch (e) { err = e }
var stack = err.stack;
console.log(String(stack[0].getFunction()));
console.log(stack[0].getLineNumber());
```

**Comment by BridgeAR** [comment]
@targos it should be fine to just change the line offset by adding `2` in case we check for the function (https://github.com/nodejs/node/blob/85898e0aca26cee2e68aea9ba384e23cd4457849/lib/assert.js#L289). That way it should be fixed again.

**Comment by targos** [comment]
maybe, but I'm afraid it's a special case when the function was created with `new Function()`. I'll try anyway, thanks.

**Comment by ryzokuken** [comment]
@targos any updates?

**Comment by targos** [comment]
No. Feel free to pick it up if you want.

**Comment by ryzokuken** [comment]
@targos Okay, I'll let you know if I decide to pick it up.

**Comment by ryzokuken** [comment]
I guess it's intentional: https://tc39.es/ecma262/#sec-createdynamicfunction
