### ISSUE TITLE
node-test-commit-node-v8 is all red, is this expected?

### ISSUE THREAD

**Issue by sam-github** [nodejs/node-v8#118]
@nodejs/v8, see https://ci.nodejs.org/view/All/job/node-test-commit-node-v8/

Poking about to see if this is expected I found:
- https://ci.nodejs.org/job/node-test-commit-linux/nodes=centos6-64-gcc6/30132/console failed becuse test-softlayer-centos6-x64-1 only has Python 2.6, and since 12.x 2.7 or later is required, see
https://github.com/nodejs/node/blob/v12.x/BUILDING.md#note-about-python-2-and-python-3  I assume this is a real problem, either that softlayer machine should be excluded from build, somehow, or it needs Python 2.7 installed.
- https://ci.nodejs.org/job/node-test-commit-osx/29273/nodes=osx1011/console fail to build ```
23:54:25 ../deps/v8/src/compiler/js-heap-broker.cc:4080:23: error: constructor for 'v8::internal::compiler::GlobalAccessFeedback' must explicitly initialize the const member 'cell_or_context_'
23:54:25 GlobalAccessFeedback::GlobalAccessFeedback(FeedbackSlotKind slot_kind)
23:54:25                       ^
23:54:25 ../deps/v8/src/compiler/processed-feedback.h:92:35: note: 'cell_or_context_' declared here
23:54:25   base::Optional<ObjectRef> const cell_or_context_;
23:54:25                                   ^
23:54:25 108 warnings and 1 error generated.```

That is not uncommon, lots of build failures were compiler errors (of different kinds), but I'm not sure if they are because the PR being built is a WIP, or if the machines lack the correct compiler versions. I've kicked off a build against master to see what the results are for it: https://ci.nodejs.org/view/All/job/node-test-commit-node-v8/353/

**Comment by targos** [comment]
I transferred this issue to the `node-v8` repo. We can talk about the existing failures and what should be done about them.

**Comment by targos** [comment]
SmartOS failure is:

```
12:32:58 dtrace: failed to compile script src/v8ustack.d: line 423: failed to resolve V8DBG_CLASS_SHAREDFUNCTIONINFO__SCRIPT_OR_DEBUG_INFO__OBJECT: Unknown variable name
```

/cc @cjihrig

**Comment by targos** [comment]
macOS failure is:

```
12:03:24 ../deps/v8/src/compiler/serializer-for-background-compilation.cc:390:12: error: constructor for 'v8::internal::compiler::Callee' must explicitly initialize the const member 'blueprint_'
12:03:24   explicit Callee(Handle<JSFunction> jsfunction) : jsfunction_(jsfunction) {}
12:03:24            ^
12:03:24 ../deps/v8/src/compiler/serializer-for-background-compilation.cc:415:43: note: 'blueprint_' declared here
12:03:24   base::Optional<FunctionBlueprint> const blueprint_;
12:03:24                                           ^
12:03:24 ../deps/v8/src/compiler/serializer-for-background-compilation.cc:391:12: error: constructor for 'v8::internal::compiler::Callee' must explicitly initialize the const member 'jsfunction_'
12:03:24   explicit Callee(FunctionBlueprint const& blueprint) : blueprint_(blueprint) {}
12:03:24            ^
12:03:24 ../deps/v8/src/compiler/serializer-for-background-compilation.cc:414:33: note: 'jsfunction_' declared here
12:03:24   MaybeHandle<JSFunction> const jsfunction_;
12:03:24                                 ^
12:03:24 2 errors generated.
```

/cc @MylesBorins

**Comment by targos** [comment]
Failure on Debian 8 is:

```
11:56:38 In file included from ../deps/v8/src/base/lazy-instance.h:73:0,
11:56:38                  from ../deps/v8/src/base/platform/condition-variable.h:9,
11:56:38                  from ../deps/v8/src/libplatform/default-foreground-task-runner.h:13,
11:56:38                  from ../deps/v8/src/libplatform/default-foreground-task-runner.cc:5:
11:56:38 ../deps/v8/src/base/macros.h:236:33: error: ‘is_trivially_copyable’ is not a member of ‘std’
11:56:38    static constexpr bool value = std::is_trivially_copyable<T>::value;
11:56:38                                  ^
11:56:38 ../deps/v8/src/base/macros.h:236:33: note: suggested alternative:
11:56:38 In file included from ../deps/v8/src/base/lazy-instance.h:73:0,
11:56:38                  from ../deps/v8/src/base/platform/condition-variable.h:9,
11:56:38                  from ../deps/v8/src/libplatform/default-foreground-task-runner.h:13,
11:56:38                  from ../deps/v8/src/libplatform/default-foreground-task-runner.cc:5:
11:56:38 ../deps/v8/src/base/macros.h:209:8: note:   ‘v8::base::is_trivially_copyable’
11:56:38  struct is_trivially_copyable {
11:56:38         ^
11:56:38 In file included from ../deps/v8/src/base/lazy-instance.h:73:0,
11:56:38                  from ../deps/v8/src/base/platform/condition-variable.h:9,
11:56:38                  from ../deps/v8/src/libplatform/default-foreground-task-runner.h:13,
11:56:38                  from ../deps/v8/src/libplatform/default-foreground-task-runner.cc:5:
11:56:38 ../deps/v8/src/base/macros.h:236:61: error: expected primary-expression before ‘>’ token
11:56:38    static constexpr bool value = std::is_trivially_copyable<T>::value;
11:56:38                                                              ^
11:56:38 ../deps/v8/src/base/macros.h:236:62: error: ‘::value’ has not been declared
11:56:38    static constexpr bool value = std::is_trivially_copyable<T>::value;
11:56:38                                                               ^
11:56:38 tools/v8_gypfiles/v8_libplatform.target.mk:137: recipe for target '/home/iojs/build/workspace/node-test-commit-linux/nodes/debian8-64/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-foreground-task-runner.o' failed
11:56:38 make[2]: *** [/home/iojs/build/workspace/node-test-commit-linux/nodes/debian8-64/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/default-foreground-task-runner.o] Error 1
```

**Comment by targos** [comment]
Test failure on alpine linux with `test.sequential/test-net-bytes-per-incoming-chunk-overhead`:

```
assert.js:378
    throw err;
    ^

AssertionError [ERR_ASSERTION]: measured 611.483648 bytes per chunk
    at process.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux/nodes/alpine-last-latest-x64/test/sequential/test-net-bytes-per-incoming-chunk-overhead.js:40:3)
    at process.emit (events.js:215:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by targos** [comment]
@cjihrig yes

**Comment by targos** [comment]
Now it's also failing on [CentOS 7](https://ci.nodejs.org/view/MyJobs/job/node-update-v8-canary/1086/console):

```
07:56:57 ../deps/v8/src/torque/instance-type-generator.cc:194:76:   required from here
07:56:57 /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/ext/new_allocator.h:120:4: error: use of deleted function ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const int; _T2 = std::unique_ptr<v8::internal::torque::{anonymous}::InstanceTypeTree>]’
07:56:57   { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
07:56:57     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
07:56:57 In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/stl_algobase.h:64:0,
07:56:57                  from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:62,
07:56:57                  from ../deps/v8/src/torque/implementation-visitor.h:8,
07:56:57                  from ../deps/v8/src/torque/instance-type-generator.cc:5:
07:56:57 /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/stl_pair.h:284:17: note: ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const int; _T2 = std::unique_ptr<v8::internal::torque::{anonymous}::InstanceTypeTree>]’ is implicitly deleted because the default definition would be ill-formed:
07:56:57        constexpr pair(const pair&) = default;
07:56:57                  ^~~~
07:56:57 /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/stl_pair.h:284:17: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = v8::internal::torque::{anonymous}::InstanceTypeTree; _Dp = std::default_delete<v8::internal::torque::{anonymous}::InstanceTypeTree>]’
07:56:57 In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
07:56:57                  from ../deps/v8/src/torque/implementation-visitor.h:8,
07:56:57                  from ../deps/v8/src/torque/instance-type-generator.cc:5:
07:56:57 /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:359:7: note: declared here
07:56:57        unique_ptr(const unique_ptr&) = delete;
07:56:57        ^~~~~~~~~~
07:56:57 tools/v8_gypfiles/torque_base.target.mk:149: recipe for target '/home/iojs/build/workspace/node-update-v8-canary/node/out/Release/obj.target/torque_base/deps/v8/src/torque/instance-type-generator.o' failed
```

**Comment by cjihrig** [comment]
@targos, please cherry-pick these commits:

- https://github.com/cjihrig/node-1/commit/ba518b980a1587165b27b59e3f7caeda4162660e - this updates V8's postmortem generation script, and I'll upstream it.
- https://github.com/cjihrig/node-1/commit/59a3ce8a34998de312ed6dcd1fc68bd610365084 - this updates the failing postmortem metadata test to use the correct constants.
- https://github.com/cjihrig/node-1/commit/ff5df8c5e32d0edb5340fd0a8374fe35363650ea - this should fix the SmartOS build.

**Comment by targos** [comment]
most issues are now fixed and we can track the remaining at https://github.com/nodejs/node/pull/30020
thanks @cjihrig for the postmortem patches
