### ISSUE TITLE
failed on test-finalization-group

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-v8#142]
Full log: https://github.com/nodejs/node-v8/runs/469163730

```
2020-02-26T08:41:02.8456224Z === release test-finalization-group ===
2020-02-26T08:41:02.8456889Z Path: parallel/test-finalization-group
2020-02-26T08:41:02.8457455Z --- stderr ---
2020-02-26T08:41:02.8458086Z /home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group.js:7
2020-02-26T08:41:02.8458479Z const g = new globalThis.FinalizationGroup(common.mustCallAtLeast(1));
2020-02-26T08:41:02.8458857Z           ^
2020-02-26T08:41:02.8459123Z 
2020-02-26T08:41:02.8459464Z TypeError: globalThis.FinalizationGroup is not a constructor
2020-02-26T08:41:02.8460142Z     at Object.<anonymous> (/home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group.js:7:11)
2020-02-26T08:41:02.8460552Z     at Module._compile (internal/modules/cjs/loader.js:1204:30)
2020-02-26T08:41:02.8460935Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1224:10)
2020-02-26T08:41:02.8461292Z     at Module.load (internal/modules/cjs/loader.js:1053:32)
2020-02-26T08:41:02.8461626Z     at Function.Module._load (internal/modules/cjs/loader.js:948:14)
2020-02-26T08:41:02.8461992Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-02-26T08:41:02.8462350Z     at internal/main/run_main_module.js:17:47
2020-02-26T08:41:02.8463528Z Command: out/Release/node --expose-gc --harmony-weak-refs /home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group.js
2020-02-26T08:41:02.8464531Z === release test-finalization-group-error ===
2020-02-26T08:41:02.8465110Z Path: parallel/test-finalization-group-error
2020-02-26T08:41:02.8465671Z --- stderr ---
2020-02-26T08:41:02.8466309Z /home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group-error.js:8
2020-02-26T08:41:02.8466690Z const g = new globalThis.FinalizationGroup(common.mustCallAtLeast(() => {
2020-02-26T08:41:02.8467053Z           ^
2020-02-26T08:41:02.8467323Z 
2020-02-26T08:41:02.8467657Z TypeError: globalThis.FinalizationGroup is not a constructor
2020-02-26T08:41:02.8468331Z     at Object.<anonymous> (/home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group-error.js:8:11)
2020-02-26T08:41:02.8468725Z     at Module._compile (internal/modules/cjs/loader.js:1204:30)
2020-02-26T08:41:02.8469103Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1224:10)
2020-02-26T08:41:02.8469467Z     at Module.load (internal/modules/cjs/loader.js:1053:32)
2020-02-26T08:41:02.8469819Z     at Function.Module._load (internal/modules/cjs/loader.js:948:14)
2020-02-26T08:41:02.8470187Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-02-26T08:41:02.8470542Z     at internal/main/run_main_module.js:17:47
2020-02-26T08:41:02.8471252Z Command: out/Release/node --expose-gc --harmony-weak-refs /home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group-error.js
2020-02-26T08:41:02.8472085Z === release test-finalization-group-regular-gc ===
```

**Comment by gengjiawen** [comment]
cc @devsnek

**Comment by targos** [comment]
@gengjiawen you may want to watch https://github.com/v8/node/ for fixes that the V8 team applies when they make backwards-incompatible changes.

**Comment by gengjiawen** [comment]
thanks.
