### ISSUE TITLE
test broken on report/test-report-fatal-error

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-v8#153]
From latest github CI pipeline.

```console
2020-04-05T07:50:54.2822967Z not ok 2611 report/test-report-fatal-error
2020-04-05T07:50:54.2823937Z   ---
2020-04-05T07:50:54.2824333Z   duration_ms: 3.131
2020-04-05T07:50:54.2824673Z   severity: fail
2020-04-05T07:50:54.2825274Z   exitcode: 1
2020-04-05T07:50:54.2825918Z   stack: |-
2020-04-05T07:50:54.2826312Z     undefined:1
2020-04-05T07:50:54.2826853Z     <--- Last few GCs --->
2020-04-05T07:50:54.2827244Z     ^
2020-04-05T07:50:54.2827544Z     
2020-04-05T07:50:54.2827871Z     SyntaxError: Unexpected token < in JSON at position 0
2020-04-05T07:50:54.2828198Z         at JSON.parse (<anonymous>)
2020-04-05T07:50:54.2830295Z         at Object.<anonymous> (/home/runner/work/node-v8/node-v8/test/report/test-report-fatal-error.js:118:21)
2020-04-05T07:50:54.2830791Z         at Module._compile (internal/modules/cjs/loader.js:1178:30)
2020-04-05T07:50:54.2831173Z         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1198:10)
2020-04-05T07:50:54.2831515Z         at Module.load (internal/modules/cjs/loader.js:1027:32)
2020-04-05T07:50:54.2831834Z         at Function.Module._load (internal/modules/cjs/loader.js:923:14)
2020-04-05T07:50:54.2832175Z         at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-04-05T07:50:54.2832514Z         at internal/main/run_main_module.js:17:47
```

**Comment by mmarchini** [comment]
Looks like a formatting change on the error.

**Comment by gengjiawen** [comment]
From what I debug, `report` is empty string for now

https://github.com/nodejs/node-v8/blob/867ff41d87e292997ff2ceb8d77e715145aed7b7/test/report/test-report-fatal-error.js#L117-L119

The node error output, perhaps and regex to match the report file ?

```console
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200407.111900.71758.0.001.json
Node.js report completed
 1: 0x1011c23b5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10009c059 node::Abort() [/usr/local/bin/node]
```

**Comment by gengjiawen** [comment]
Looks like this is a way to fix: 

```js
  const report = lines.find(i => i.startsWith("{"));
```
