### ISSUE TITLE
two test related to finalization group failed

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-v8#155]
```console
not ok 702 parallel/test-finalization-group
  ---
  duration_ms: 0.414
  severity: fail
  exitcode: 1
  stack: |-
    /home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group.js:12
      g.cleanupSome();
        ^
    
    TypeError: g.cleanupSome is not a function
        at Timeout._onTimeout (/home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group.js:12:5)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7)
  ...
not ok 703 parallel/test-finalization-group-error
  ---
  duration_ms: 0.410
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched noop function calls. Expected exactly 1, actual 2.
        at Proxy.mustCall (/home/runner/work/node-v8/node-v8/test/common/index.js:328:10)
        at Object.<anonymous> (/home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group-error.js:27:40)
        at Module._compile (internal/modules/cjs/loader.js:1178:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1198:10)
        at Module.load (internal/modules/cjs/loader.js:1027:32)
        at Function.Module._load (internal/modules/cjs/loader.js:923:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
        at internal/main/run_main_module.js:17:47
  ...
```

**Comment by jkrems** [comment]
Should those tests be removed/disabled? It feels weird that node's tests would be sensitive to language features that are still being worked out (stage 3 but barely so).

**Comment by devsnek** [comment]
As long as node specializes weakref cleanup in some way (which we do, see Environment::RunWeakRefCleanup) we should keep the tests. They will need to be updated as the proposal and v8 are updated though.

**Comment by gengjiawen** [comment]
This one still failed:
cc @mmarchini  
```console
=== release test-finalization-group-error ===
Path: parallel/test-finalization-group-error
--- stdout ---
Mismatched noop function calls. Expected exactly 1, actual 2.
    at Proxy.mustCall (/home/runner/work/node-v8/node-v8/test/common/index.js:328:10)
    at Object.<anonymous> (/home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group-error.js:27:40)
    at Module._compile (internal/modules/cjs/loader.js:1178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1198:10)
    at Module.load (internal/modules/cjs/loader.js:1027:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Command: out/Release/node --expose-gc --harmony-weak-refs /home/runner/work/node-v8/node-v8/test/parallel/test-finalization-group-error.js
```

**Comment by mmarchini** [comment]
Oh no, this will keep closing because of the daily job :joy:

We should another issue for `test-finalization-group-error`

**Comment by gengjiawen** [comment]
> Oh no, this will keep closing because of the daily job 😂
> 
> We should another issue for `test-finalization-group-error`

😂😂😂
