### ISSUE TITLE
Abort on uncaught exception broken on Windows?

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#197]
See https://ci.nodejs.org/job/node-test-binary-windows-js-suites/9097/#showFailuresLink

Example failure:
```
node:assert:122
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 2147483651
- 3221225477
    at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\abort\test-abort-uncaught-exception.js:31:16)
    at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:388:15)
    at ChildProcess.emit (node:events:369:20)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 2147483651,
  expected: 3221225477,
  operator: 'strictEqual'
}
```

**Comment by targos** [comment]
@nodejs/platform-windows

**Comment by targos** [comment]
Moving discussion to https://github.com/nodejs/node/pull/38273#issuecomment-826059171
