### ISSUE TITLE
`test/addons/make-callback-recurse` failure

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#272]
```
$ out/Release/node /Users/mzasso/git/nodejs/canary/test/addons/make-callback-recurse/test.js
node:assert:126
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'UNREACHABLE'
- 'throw from domain 3'
    at Domain.<anonymous> (/Users/mzasso/git/nodejs/canary/test/addons/make-callback-recurse/test.js:138:14)
    at Domain.<anonymous> (/Users/mzasso/git/nodejs/canary/test/common/index.js:476:15)
    at Domain.emit (node:events:519:28)
    at Domain.emit (node:domain:488:12)
    at Domain._errorHandler (node:domain:278:23)
    at Object.<anonymous> (node:domain:180:29)
    at process._fatalException (node:internal/process/execution:177:29) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 'UNREACHABLE',
  expected: 'throw from domain 3',
  operator: 'strictEqual'
}

Node.js v22.0.0-pre
```

**Comment by targos** [comment]
Still failing: https://github.com/nodejs/node-v8/actions/runs/7297300031/job/19886341295

@nodejs/addon-api @nodejs/node-api

**Comment by targos** [comment]
Fixed in https://github.com/nodejs/node/pull/51362/commits/9570832ae8650b73e04c2a0347b07cd6c19de15b
