### ISSUE TITLE
Test failures on canary

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#44]
CI run: https://ci.nodejs.org/job/node-test-commit-linux/17279/nodes=centos7-64/console

```
05:25:12 not ok 1218 parallel/test-postmortem-metadata # TODO : Fix flaky test
05:25:12   ---
05:25:12   duration_ms: 1.949
05:25:12   severity: flaky
05:25:12   stack: |-
05:25:12     assert.js:80
05:25:12       throw new AssertionError(obj);
05:25:12       ^
05:25:12     
05:25:12     AssertionError [ERR_ASSERTION]: Missing constants: v8dbg_class_SharedFunctionInfo__raw_name__Object,v8dbg_class_SharedFunctionInfo__scope_info__ScopeInfo
05:25:12         at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux/nodes/centos7-64/test/parallel/test-postmortem-metadata.js:48:8)
05:25:12         at Module._compile (internal/modules/cjs/loader.js:677:30)
05:25:12         at Object.Module._extensions..js (internal/modules/cjs/loader.js:688:10)
05:25:12         at Module.load (internal/modules/cjs/loader.js:588:32)
05:25:12         at tryModuleLoad (internal/modules/cjs/loader.js:527:12)
05:25:12         at Function.Module._load (internal/modules/cjs/loader.js:519:3)
05:25:12         at Function.Module.runMain (internal/modules/cjs/loader.js:718:10)
05:25:12         at startup (internal/bootstrap/node.js:225:19)
05:25:12         at bootstrapNodeJSCore (internal/bootstrap/node.js:570:3)
05:25:12   ...
```

```
05:26:16 not ok 1716 parallel/test-v8-stats
05:26:16   ---
05:26:16   duration_ms: 0.139
05:26:16   severity: fail
05:26:16   stack: |-
05:26:16     assert.js:80
05:26:16       throw new AssertionError(obj);
05:26:16       ^
05:26:16     
05:26:16     AssertionError [ERR_ASSERTION]: [ 'code_space',
05:26:16       'large_object_space',
05:26:16       'map_space',
05:26:16       'new_space',
05:26:16       'old_space',
05:26:16       'read_only_space' ] deepStrictEqual [ 'code_space',
05:26:16       'large_object_space',
05:26:16       'map_space',
05:26:16       'new_space',
05:26:16       'old_space' ]
05:26:16         at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux/nodes/centos7-64/test/parallel/test-v8-stats.js:32:8)
05:26:16         at Module._compile (internal/modules/cjs/loader.js:677:30)
05:26:16         at Object.Module._extensions..js (internal/modules/cjs/loader.js:688:10)
05:26:16         at Module.load (internal/modules/cjs/loader.js:588:32)
05:26:16         at tryModuleLoad (internal/modules/cjs/loader.js:527:12)
05:26:16         at Function.Module._load (internal/modules/cjs/loader.js:519:3)
05:26:16         at Function.Module.runMain (internal/modules/cjs/loader.js:718:10)
05:26:16         at startup (internal/bootstrap/node.js:225:19)
05:26:16         at bootstrapNodeJSCore (internal/bootstrap/node.js:570:3)
05:26:16   ...
```

**Comment by cjihrig** [comment]
I can look into this one.

**Comment by cjihrig** [comment]
Fixes in https://github.com/nodejs/node-v8/pull/47
