### ISSUE TITLE
Missing postmortem constant

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-v8#67]
Missing `v8dbg_scopeinfo_idx_nstacklocals`

```
08:57:35 not ok 1 v8-updates/test-postmortem-metadata
08:57:35   ---
08:57:35   duration_ms: 1.15
08:57:35   severity: fail
08:57:35   exitcode: 1
08:57:35   stack: |-
08:57:35     assert.js:80
08:57:35       throw new AssertionError(obj);
08:57:35       ^
08:57:35     
08:57:35     AssertionError [ERR_ASSERTION]: Missing constants: v8dbg_scopeinfo_idx_nstacklocals
08:57:35         at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-custom-suites/default/test/v8-updates/test-postmortem-metadata.js:48:8)
08:57:35         at Module._compile (internal/modules/cjs/loader.js:689:30)
08:57:35         at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
08:57:35         at Module.load (internal/modules/cjs/loader.js:599:32)
08:57:35         at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
08:57:35         at Function.Module._load (internal/modules/cjs/loader.js:530:3)
08:57:35         at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
08:57:35         at startup (internal/bootstrap/node.js:260:19)
08:57:35         at bootstrapNodeJSCore (internal/bootstrap/node.js:584:3)
```

https://ci.nodejs.org/job/node-test-commit-custom-suites/47/default/console

**Comment by targos** [comment]
Fixed by https://github.com/nodejs/node/commit/cbe37b238c7134b46d8f4657bd930bd83581c597
