### ISSUE TITLE
Need help to unbreak canary builds

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#69]
The canary branch is currently broken because https://github.com/nodejs/node-v8/commit/714c686f422be53540c751bfc8463f60b593aee0#diff-91081f7e2c43274462308861f4191e3b is no longer valid after recent changes to `test/cctest/node_test_fixture.h` on master.
Would someone be able to help me unbreak it?

**Comment by addaleax** [comment]
Is d6f7a32570994b21c628b517b3ddc863a1f059fb the conflicting change? I think it might be enough for now to remove the first part of the diff linked above in `test/cctest/node_test_fixture.h`?

**Comment by targos** [comment]
> Is d6f7a32 the conflicting change? 

Yes.

> I think it might be enough for now to remove the first part of the diff linked above in test/cctest/node_test_fixture.h?

You mean to not add the two lines in `SetUp`? I tried to do that and the test crashes:

```
[==========] Running 74 tests from 9 test cases.
[----------] Global test environment set-up.
[----------] 14 tests from AliasBufferTest
[ RUN      ] AliasBufferTest.Uint8Array
Segmentation fault (core dumped)
Makefile:238: recipe for target 'cctest' failed
make: *** [cctest] Error 139
```

**Comment by addaleax** [comment]
Ok, I’ll look into it … should be doable :crossed_fingers:

**Comment by danbev** [comment]
Sorry about this! @addaleax Let me know if there is anything I can help out with. Thanks

**Comment by danbev** [comment]
@addaleax I took a look and have a suggestion linked above. Feel free to ignore you have already started looking into this. I did not mean to step on your toes here, just felt bad bad that you are having to spend time fixing issues that I caused.

**Comment by addaleax** [comment]
@targos Can you confirm that the linked patch works, at least as a temporary workaround?

**Comment by targos** [comment]
@addaleax, @danbev. It does work, thanks!

I pushed the commit to canary: https://github.com/nodejs/node-v8/commit/c538b12bf889b4edb3d8208a0f6cdb3f07316669 and a subsequent one to fix a test (unrelated to this issue): https://github.com/nodejs/node-v8/commit/0f69779e0361307e14395e1f7c761c734243d189

**Comment by targos** [comment]
Now, lkgr has advanced and I'm experiencing a new issue!

I pushed the current state to canary-base: https://github.com/nodejs/node/commits/canary-base.

Something related to ICU changed upstream, probably related to this commit: https://github.com/v8/v8/commit/3ba5445b8a0e31a0f45d9268286216da0c8dfe89#diff-4eaebbcd1dc0da11e3a3ce488290bfc6

Here is one of the errors I get:
```
In file included from ../deps/v8/src/interface-descriptors.h:12,
                 from ../deps/v8/src/callable.h:9,
                 from ../deps/v8/src/code-factory.h:10,
                 from ../deps/v8/src/compiler/code-assembler.h:16,
                 from ../deps/v8/src/code-stub-assembler.h:11,
                 from ../deps/v8/src/builtins/builtins-arguments-gen.h:8,
                 from ../deps/v8/src/builtins/builtins-arguments-gen.cc:5:
../deps/v8/src/isolate.h:36:10: fatal error: unicode/uversion.h: No such file or directory
 #include "unicode/uversion.h"  // Define U_ICU_NAMESPACE.
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [deps/v8/gypfiles/v8_initializers.target.mk:167: /home/mzasso/git/nodejs/canary/out/Release/obj.target/v8_initializers/deps/v8/src/builtins/builtins-arguments-gen.o] Error 1
```

**Comment by srl295** [comment]
@addaleax i'm concerned about the inclusion of the icu deps folder.  `v8_enable_i18n_support` is turned on but we are changing which ICU is built. Seems like a v8 bug.

**Comment by targos** [comment]
I think I understand what the problem is. After that commit, when `v8_enable_i18n_support` is turned on, more targets need to include ICU, similar to how it's done here for the main target:
https://github.com/nodejs/node/blob/45732c7c19672869a7e517e252c83b371a863bee/deps/v8/gypfiles/v8.gyp#L1820-L1824

**Comment by srl295** [comment]
That makes sense. The v8 change is to move more stuff to C++.

more stuff off without ICU..

**Comment by targos** [comment]
/cc @nodejs/gyp

Tentative fix: https://github.com/targos/node/commit/adf23f2efb02ace58052d65d1e41a0d5b763b079

Now I see this error:

```
  g++ '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=0' '-DV8_TARGET_ARCH_X64' '-DV8_EMBEDDER_STRING="-node.1"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT' '-Dv8_promise_internal_field_count' '-DV8_INTL_SUPPORT' '-DV8_CONCURRENT_MARKING' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../. -I/home/mzasso/git/nodejs/canary/out/Release/obj/gen -I../deps/v8/include -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -fno-strict-aliasing -m64 -fdata-sections -ffunction-sections -O3 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF /home/mzasso/git/nodejs/canary/out/Release/.deps//home/mzasso/git/nodejs/canary/out/Release/obj.target/v8_base/deps/v8/src/objects/intl-objects.o.d.raw   -c -o /home/mzasso/git/nodejs/canary/out/Release/obj.target/v8_base/deps/v8/src/objects/intl-objects.o ../deps/v8/src/objects/intl-objects.cc
In file included from ../deps/v8/src/debug/debug.h:19,
                 from ../deps/v8/src/wasm/wasm-objects.h:9,
                 from ../deps/v8/src/wasm/wasm-objects-inl.h:8,
                 from ../deps/v8/src/objects/shared-function-info-inl.h:13,
                 from ../deps/v8/src/objects/templates-inl.h:11,
                 from ../deps/v8/src/objects/map-inl.h:16,
                 from ../deps/v8/src/contexts-inl.h:12,
                 from ../deps/v8/src/objects-inl.h:21,
                 from ../deps/v8/src/objects/intl-objects.cc:19:
../deps/v8/src/frames.h: In member function ‘void v8::internal::InnerPointerToCodeCache::Flush()’:
../deps/v8/src/frames.h:46:41: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry’; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(&cache_[0], 0, sizeof(cache_));
                                         ^
../deps/v8/src/frames.h:35:10: note: ‘struct v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry’ declared here
   struct InnerPointerToCodeCacheEntry {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/v8/src/objects/intl-objects.cc: In function ‘void v8::internal::BuildLanguageTagRegexps(v8::internal::Isolate*)’:
../deps/v8/src/objects/intl-objects.cc:1350:73: error: invalid use of incomplete type ‘class icu_62::RegexMatcher’
       icu::UnicodeString::fromUTF8(language_singleton_regexp), 0, status);
                                                                         ^
In file included from ../deps/v8/src/api.h:13,
                 from ../deps/v8/src/objects/intl-objects.cc:14:
../deps/v8/src/isolate.h:40:7: note: forward declaration of ‘class icu_62::RegexMatcher’
 class RegexMatcher;
       ^~~~~~~~~~~~
../deps/v8/src/objects/intl-objects.cc:1352:67: error: invalid use of incomplete type ‘class icu_62::RegexMatcher’
       icu::UnicodeString::fromUTF8(language_tag_regexp), 0, status);
                                                                   ^
In file included from ../deps/v8/src/api.h:13,
                 from ../deps/v8/src/objects/intl-objects.cc:14:
../deps/v8/src/isolate.h:40:7: note: forward declaration of ‘class icu_62::RegexMatcher’
 class RegexMatcher;
       ^~~~~~~~~~~~
../deps/v8/src/objects/intl-objects.cc:1354:71: error: invalid use of incomplete type ‘class icu_62::RegexMatcher’
       icu::UnicodeString::fromUTF8(language_variant_regexp), 0, status);
                                                                       ^
In file included from ../deps/v8/src/api.h:13,
                 from ../deps/v8/src/objects/intl-objects.cc:14:
../deps/v8/src/isolate.h:40:7: note: forward declaration of ‘class icu_62::RegexMatcher’
 class RegexMatcher;
       ^~~~~~~~~~~~
make[1]: *** [deps/v8/gypfiles/v8_base.target.mk:633: /home/mzasso/git/nodejs/canary/out/Release/obj.target/v8_base/deps/v8/src/objects/intl-objects.o] Error 1
rm fc4b5a95735baed148f443409c7e3e4931bc56c2.intermediate d3bc80f7856fcfa3d3d7905265a41fb78f6975d6.intermediate 6c8bbb6e9dc9d22d3b7b17a57b2f4f14600c74e4.intermediate
make: *** [Makefile:87: node] Error 2
```

**Comment by srl295** [comment]
for reference, v8's bump to 62.1 https://chromium-review.googlesource.com/c/v8/v8/+/1111857#message-4f92f63a195703cf7cc65aea74efa2f9b8163f2d

**Comment by srl295** [comment]
@targos i finally realized there's a `test-v8-intl` …

**Comment by targos** [comment]
Ping @nodejs/v8-update. Would someone be able to help with this forward declaration issue?

**Comment by addaleax** [comment]
@targos I couldn’t reproduce that failure when building the current `canary` … sounds like adding `#include "unicode/regex.h"` in the failing file might be enough though?

**Comment by targos** [comment]
@addaleax you can try with [`canary-base`](https://github.com/nodejs/node/commits/canary-base) or [`my branch`](https://github.com/targos/node/commits/canary-fix-icu) that has one additional commit.

**Comment by addaleax** [comment]
```diff
diff --git a/src/heap_utils.cc b/src/heap_utils.cc
index 2d339c580fa0..ead3716daf44 100644
--- a/src/heap_utils.cc
+++ b/src/heap_utils.cc
@@ -76,7 +76,7 @@ class JSGraph : public EmbedderGraph {
     return n;
   }
 
-  void AddEdge(Node* from, Node* to) override {
+  void AddEdge(Node* from, Node* to, const char* name) override {
     edges_[from].insert(to);
   }
 
diff --git a/tools/icu/icu-generic.gyp b/tools/icu/icu-generic.gyp
index a50f12d7940b..2acc95b409b8 100644
--- a/tools/icu/icu-generic.gyp
+++ b/tools/icu/icu-generic.gyp
@@ -32,7 +32,6 @@
       'direct_dependent_settings': {
         'defines': [
           'UCONFIG_NO_SERVICE=1',
-          'UCONFIG_NO_REGULAR_EXPRESSIONS=1',
           'U_ENABLE_DYLOAD=0',
           'U_STATIC_IMPLEMENTATION=1',
           'U_HAVE_STD_STRING=1',
```

seems to do the trick for me on your branch :tada:

**Comment by targos** [comment]
Awesome, thank you! I had to fix a few other things but finally got it to compile :)

Update build: https://ci.nodejs.org/view/MyJobs/job/node-update-v8-canary/531/console

**Comment by vsemozhetbyt** [comment]
Is it expected that we still have not new builds in https://nodejs.org/download/v8-canary/ ?

**Comment by targos** [comment]
It's not. Let me check the release CI

**Comment by targos** [comment]
The release job ends like this (Linux, x64):

```
/home/iojs/build/ws/out/Release/obj.target/tools/icu/libicustubdata.a /home/iojs/build/ws/out/Release/obj.target/deps/v8/gypfiles/libv8_snapshot.a -ldl -lrt -lm -Wl,--end-group
rm d9c769d7502516ddb3e9d8667cc1789f214a1de0.intermediate 5c22b76bd1702bf27ee3595fb52b5998f72abac8.intermediate 697d8a3ed98f6d25534e6e9073f38cfd5cfaedcb.intermediate
if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
/usr/bin/python tools/install.py install 'node-v11.0.0-v8-canary201807245d62d23af4-linux-x64' '/'
installing /home/iojs/build/ws/node-v11.0.0-v8-canary201807245d62d23af4-linux-x64/bin/node
installing /home/iojs/build/ws/node-v11.0.0-v8-canary201807245d62d23af4-linux-x64/share/systemtap/tapset/node.stp
installing /home/iojs/build/ws/node-v11.0.0-v8-canary201807245d62d23af4-linux-x64/share/doc/node/gdbinit
installing /home/iojs/build/ws/node-v11.0.0-v8-canary201807245d62d23af4-linux-x64/share/doc/node/lldbinit
Traceback (most recent call last):
  File "tools/install.py", line 225, in <module>
    run(sys.argv[:])
  File "tools/install.py", line 219, in run
    if cmd == 'install': return files(install)
  File "tools/install.py", line 147, in files
    action(['deps/v8/tools/lldbinit'], 'share/doc/node/')
  File "tools/install.py", line 74, in install
    def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
  File "tools/install.py", line 74, in <lambda>
    def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
  File "tools/install.py", line 66, in try_copy
    return shutil.copy2(source_path, target_path)
  File "/usr/lib64/python2.6/shutil.py", line 95, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 50, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'deps/v8/tools/lldbinit'
Makefile:126: recipe for target 'install' failed
make[1]: *** [install] Error 1
Makefile:1003: recipe for target 'node-v11.0.0-v8-canary201807245d62d23af4-linux-x64.tar' failed
make: *** [node-v11.0.0-v8-canary201807245d62d23af4-linux-x64.tar] Error 2
Build step 'Conditional steps (multiple)' marked build as failure
Skipped archiving because build is not successful
Sending e-mails to: michael_dawson@ca.ibm.com
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by targos** [comment]
lldbinit was removed in https://github.com/v8/v8/commit/3255d8dd4197c986b5fd290356cd575fb3234e00
Refs: https://github.com/v8/node/pull/75

I'm going to cherry-pick the commit to canary for new but we'll need to discuss the impact of this change when we upgrade to this version of V8.

**Comment by targos** [comment]
New build with that commit: https://ci-release.nodejs.org/job/iojs+release/3593/

**Comment by targos** [comment]
@vsemozhetbyt https://nodejs.org/download/v8-canary/v11.0.0-v8-canary201807247c08774a29/

OSX build still absent (https://github.com/nodejs/build/pull/1409 fill fix it)
Windows build fails like this:
```
  mksnapshot.cc
     Creating library c:\ws\Release\mksnapshot.lib and object c:\ws\Release\mksnapshot.exp
v8_base_2.lib(isolate.obj) : error LNK2001: unresolved external symbol "unsigned int __cdecl v8::internal::DefaultEmbeddedBlobSize(void)" (?DefaultEmbeddedBlobSize@internal@v8@@YAIXZ) [c:\ws\deps\v8\gypfiles\mksnapshot.vcxproj]
v8_base_2.lib(isolate.obj) : error LNK2001: unresolved external symbol "unsigned char const * __cdecl v8::internal::DefaultEmbeddedBlob(void)" (?DefaultEmbeddedBlob@internal@v8@@YAPEBEXZ) [c:\ws\deps\v8\gypfiles\mksnapshot.vcxproj]
c:\ws\Release\mksnapshot.exe : fatal error LNK1120: 2 unresolved externals [c:\ws\deps\v8\gypfiles\mksnapshot.vcxproj]
```

**Comment by vsemozhetbyt** [comment]
Thank you! Hope Windows builds will come around in some days)

**Comment by targos** [comment]
I opened https://github.com/nodejs/node-v8/issues/71 to track the Windows failure

**Comment by vsemozhetbyt** [comment]
Thank you!
