### ISSUE TITLE
Missing postmortem constants

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#70]
```
$ ./node test/v8-updates/test-postmortem-metadata.js
assert.js:84
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Missing constants: v8dbg_class_SharedFunctionInfo__end_position__int,v8dbg_class_SharedFunctionInfo__function_identifier__Object,v8dbg_class_SharedFunctionInfo__script__Object,v8dbg_class_SharedFunctionInfo__start_position_and_type__int,v8dbg_sharedfunctioninfo_start_position_mask,v8dbg_sharedfunctioninfo_start_position_shift
    at Object.<anonymous> (/home/mzasso/git/nodejs/canary/test/v8-updates/test-postmortem-metadata.js:48:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

**Comment by mmarchini** [comment]
Oh my, that's a lot of changes 😥

**Comment by targos** [comment]
Closing in favor of https://github.com/nodejs/node/pull/21983
